spring:
  config:
    activate:
      on-profile: prod
  application:
    name: freelance-resource-backend
  datasource:
    url: "jdbc:mysql://${DATABASE_HOST:db}:${DATABASE_PORT:3306}/${DATABASE_NAME:user}"
    username: root
    password: root
  jpa:
    show-sql: "${JPA_SHOW_SQL:false}"
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "${JWK_SET_URI:http://localhost:9000/oauth2/jwks}"

app:
  version: "1.0"

accounts:
  message: "test message"
  details:
    name: "Kuan"
    email: "test@example.com"
  support:
    - 123456789
    - 987654321